version: '3.9'

services:
  python-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./datasets:/app/datasets
      - ./code:/app/code  # Mounting the 'code' folder
    working_dir: /app
    stdin_open: true
    tty: true
    environment:
      KAFKA_BROKER: "kafka:29092"  # Using Kafka's internal Docker network
    networks:
      - kafka_docker_kafka-network  # Connect to Kafka's network

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''
    ports:
      - "8888:8888"
    volumes:
      - ./:/app
      - ./datasets:/app/datasets  # Mounting the 'datasets' folder
      - ./code:/app/code   # Mounting the 'code' folder
    working_dir: /app
    environment:
      KAFKA_BROKER: "kafka:29092"  # Using Kafka's internal Docker network
    networks:
      - kafka_docker_kafka-network  # Connect to Kafka's network

networks:
  kafka_docker_kafka-network:
    external: true  # Ensure it connects to Kafka's network