apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: "neuron-0-0"
  namespace: knative-serving
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "1"
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/max-scale: "1"
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "1h"
    spec:
      containerConcurrency: 1
      containers:
        - image: registry.example.com/python-function:latest
          env:
            - name: FUNCTION_ID
              value: "${FUNCTION_ID}"
            - name: PARAMS
              value: '${PARAMS_JSON}'
          envFrom:
            - secretRef:
                name: function-env-secret
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: ${FUNCTION_ID}-trigger
  namespace: knative-eventing
spec:
  broker: kafka-broker
  filter:
    attributes:
      # exact source that KafkaSource emits for this topic:
      source: "/apis/v1/namespaces/knative-eventing/kafkasources/${AUTOSCALER_ID}"
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: "${FUNCTION_ID}"
